### PR TITLE
Call XSetInputFocus on clients that are made active

### PR DESCRIPTION
**Pull request by IMbackK**
fixes [#346](https://github.com/maemo-leste/bugtracker/issues/346) in a better place

### CODE REVIEW

**Comment by freemangordon** [comment]
Could you please elaborate on what is the problem and how and why the fix works? It is not that I am nitpicking, but because it take me a couple of months to come-up with https://github.com/maemo-leste/hildon-desktop-clutter-1.x/commit/ccb3cddaf81949ef1bcb18921858e72fcef97e5b and I have the feeling it is something similar here. But without having the bigger picture I can't be sure.

**Comment by IMbackK** [comment]
Hi, so on raising a window via pager hildon calls libmachbox2 mb_wm_activate_client_real  witch ends up in mb_wm_client_set_focus if the window has set the wants focus flag. If the window supports the hint libmatchbox will then not focus the window directly via XSetInputFocus but will pass WM_TAKE_FOCUS to the window. This is in order to allow the application to choose a different window it wants focused instead, eg a dialog or something. the inspec thing to do for the application to send _NET_ACTIVE_WINDOW to the root window with the window it wants focust. This is handled by mb_wm_root_window_handle_message witch gets passed to  mb_wm_main_context_handle_x_event from hildon in clutter_x11_event_filter. However for some reason unkown to me the event never reaches clutter_x11_event_filter, while other events do reach this function. 

So this patch simply avoids applications sending _NET_ACTIVE_WINDOW by never sending WM_TAKE_FOCUS. Also the logic behind whitch windows to send WM_TAKE_FOCUS is fragile and missdetects xev as supporting EWMH, making the whole thing a bad idea in the first place.

**Comment by MerlijnWajer** [comment]
So I added this to libmatchbox2, built it, installed it, built hildon-desktop with this libmatchbox2, but xev and glxgears (for example) still do not get keyboard focus.

It does allow typing in Qt input fields.

**Comment by MerlijnWajer** [comment]
One thing to potentially keep in mind is that, as far as I can tell:

1. Events flow from clutter to h-d to matchbox.
2. h-d has an X11 event handler installed in clutter which runs before clutters own event handler
3. h-d never tells clutter to drop any events when it deals with events
4. clutter does act on some important events

It is not impossible (I have not verified this at all), that after matchbox deals with some focus event, clutter also tries to act on it. But as far I as I understood from IRC earlier today, the problem is that hildon-desktop never sees this particular event, which means clutter should filter it, but from clutter code, the first thing it should do is call hildon-desktop's x11 event filter.

Perhaps clutter is not getting the event from X11 if it has the wrong protocols set. It does seem to act on those events.

**Comment by MerlijnWajer** [comment]
Clutter also filters certain events, but I am not sure if those go to individual windows (I am flying partially blind here), but for example, clutter doesn't seem to pass *any* WM_PROTOCOLS information on:

```
  /* do not send any of the WM_PROTOCOLS events to the queue */
  return FALSE;
```

But I am not sure if that means it doesn't pass that information on to all windows, or to something else.

**Comment by MerlijnWajer** [comment]
It also seems to catch FocusIn events, and specifically not pass those on:

```
    case FocusIn:
      if (!(stage_x11->state & CLUTTER_STAGE_STATE_ACTIVATED))
        {
          /* TODO: check xevent->xfocus.detail ? */
          stage_x11->state |= CLUTTER_STAGE_STATE_ACTIVATED;

          event->type = CLUTTER_STAGE_STATE;
          event->stage_state.changed_mask = CLUTTER_STAGE_STATE_ACTIVATED;
          event->stage_state.new_state = stage_x11->state;
        }
      else
        res = FALSE;
      break;

    case FocusOut:
      if (stage_x11->state & CLUTTER_STAGE_STATE_ACTIVATED)
        {
          stage_x11->state &= ~CLUTTER_STAGE_STATE_ACTIVATED;

          event->type = CLUTTER_STAGE_STATE;
          event->stage_state.changed_mask = CLUTTER_STAGE_STATE_ACTIVATED;
          event->stage_state.new_state = stage_x11->state;
        }
      else
        res = FALSE;
      break;
```

But again, those might be for something else. But it's a bit suspect.

**Comment by freemangordon** [comment]
Is this still relevant in light of https://github.com/maemo-leste/libmatchbox2/pull/4 ?

**Comment by MerlijnWajer** [comment]
Yes, because this is required for Qt and others to work.

**Pull request merged**
